package ocean.compiler;

import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Metadata annotation emitted on JVM class files generated by the Ocean compiler.
 * <p>
 * Stores essential compiler metadata including language name, compiler version,
 * language specification version, original source file name, and class kind.
 */
@Documented
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.TYPE)
public @interface Metadata {

    // ─────────────────────────────────────────────────────────────────────────────
    //  Class Kind Constants
    // ─────────────────────────────────────────────────────────────────────────────
    int KIND_CLASS = 1;
    int KIND_INTERFACE = 2;
    int KIND_ENUM = 3;
    int KIND_DATA_CLASS = 4;
    int KIND_RECORD = 5;
    int KIND_ANNOTATION = 6;

    /**
     * Language identifier, always {@code "ocean"}.
     */
    String language() default "ocean";

    /**
     * Compiler version that emitted the bytecode (e.g. {@code "1.0.0"}).
     */
    String compilerVersion() default "1.0.0";

    /**
     * Ocean language specification / bytecode format version (e.g. {@code 1}).
     */
    int languageVersion() default 1;

    /**
     * Sınıf türü / Class kind:
     * <ul>
     *   <li>{@link #KIND_CLASS} (1): Standart sınıf (Standard Class)</li>
     *   <li>{@link #KIND_INTERFACE} (2): Arayüz (Interface)</li>
     *   <li>{@link #KIND_ENUM} (3): Numaralandırma (Enum)</li>
     *   <li>{@link #KIND_DATA_CLASS} (4): Veri sınıfı (Data Class)</li>
     *   <li>{@link #KIND_RECORD} (5): Record</li>
     *   <li>{@link #KIND_ANNOTATION} (6): Notasyon (Annotation)</li>
     * </ul>
     */
    int kind() default KIND_CLASS;

    /**
     * Orijinal .ocean kaynak dosyası adı (örneğin {@code "Main.ocean"}).
     */
    String sourceFile() default "";

    /**
     * Reserved for forward compatibility (e.g., serialized symbols, nullability info).
     */
    String[] data() default {};

    /**
     * Additional bitwise compiler flags.
     */
    int flags() default 0;
}
