package ocean.compiler;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.objectweb.asm.ClassReader;
import org.objectweb.asm.util.CheckClassAdapter;

import java.io.PrintWriter;
import java.io.StringWriter;
import java.lang.reflect.Method;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

class JlsAuditProbeTest extends CompilerTestHelper {

    @Test
    @DisplayName("Static field and static initializer execution order follows declaration order")
    void staticInitializationOrder() throws Exception {
        Class<?> clazz = compileAndLoad("StaticInitializationOrder", """
                public class StaticInitializationOrder {
                    static int trace = 1;
                    static {
                        trace = trace * 10 + 2;
                    }
                    static int third = trace = trace * 10 + 3;

                    public static int function value() {
                        return trace;
                    }
                }
                """);

        Method value = clazz.getMethod("value");
        assertEquals(123, value.invoke(null));
    }

    @Test
    @DisplayName("Instance field and instance initializer execution order follows declaration order")
    void instanceInitializationOrder() throws Exception {
        Map<String, Class<?>> loaded = compileAndLoadAll("JlsAuditInstance", """
                public class JlsAuditInstance {
                    int trace = 1;
                    {
                        trace = trace * 10 + 2;
                    }
                    int third = trace = trace * 10 + 3;

                    public int function value() {
                        return trace;
                    }
                }
                """);
        Class<?> clazz = loaded.get("JlsAuditInstance");

        Object instance = clazz.getConstructor().newInstance();
        Method value = clazz.getMethod("value");
        assertEquals(123, value.invoke(instance));
    }

    @Test
    @DisplayName("Method arguments are evaluated from left to right")
    void methodArgumentsAreEvaluatedLeftToRight() throws Exception {
        Class<?> clazz = compileAndLoad("ArgumentEvaluationOrder", """
                public class ArgumentEvaluationOrder {
                    static int trace = 0;

                    public static int function next(int value) {
                        trace = trace * 10 + value;
                        return value;
                    }

                    public static int function pack(int a, int b, int c) {
                        return trace;
                    }

                    public static int function value() {
                        trace = 0;
                        return pack(next(1), next(2), next(3));
                    }
                }
                """);

        Method value = clazz.getMethod("value");
        assertEquals(123, value.invoke(null));
    }

    @Test
    @DisplayName("Member type cannot reuse an enclosing type name")
    void memberTypeCannotReuseEnclosingTypeName() {
        CompilationException exception = assertThrows(CompilationException.class,
                () -> compileToBytecodeMap("""
                        public class Outer {
                            class Outer {}
                        }
                        """, "Outer"));
        assertTrue(exception.getMessage().contains("Inner class cannot have the same name as outer class."));
    }

    @Test
    @DisplayName("Generated bytecode passes ASM structural verification")
    void generatedBytecodePassesStructuralVerification() {
        Map<String, byte[]> bytecode = compileToBytecodeMap("""
                public class BytecodeVerificationProbe {
                    public static int function value(int input) {
                        int total = 0;
                        while (input > 0) {
                            trying {
                                total += input;
                            } finally {
                                input--;
                            }
                        }
                        return total;
                    }
                }
                """, "BytecodeVerificationProbe");

        for (Map.Entry<String, byte[]> entry : bytecode.entrySet()) {
            StringWriter errors = new StringWriter();
            CheckClassAdapter.verify(new ClassReader(entry.getValue()), false, new PrintWriter(errors));
            assertTrue(errors.toString().isBlank(),
                    () -> "ASM verifier rejected " + entry.getKey() + ": " + errors);
        }
    }

    @Test
    @DisplayName("Protected member is accessible through this in a subclass")
    void protectedMemberIsAccessibleThroughThisInSubclass() {
        assertDoesNotThrow(() -> compileToBytecodeMap("""
                public class ProtectedBase {
                    protected int value = 7;
                }
                public class ProtectedChild extends ProtectedBase {
                    public int function read() {
                        return this.value;
                    }
                }
                """, "ProtectedChild"));
    }

    @Test
    @DisplayName("Chained assignments evaluate and assign right-associatively")
    void chainedAssignmentsEvaluateAndAssignRightAssociatively() throws Exception {
        Class<?> clazz = compileAndLoad("ChainedAssignmentProbe", """
                public class ChainedAssignmentProbe {
                    public static int function testLocal() {
                        int a = 0;
                        int b = 0;
                        int c = 0;
                        a = b = c = 42;
                        return a + b + c;
                    }

                    public static int function testNested() {
                        int x = 10;
                        int y = 20;
                        int z = (x = 5) + (y = x * 2);
                        return z + x + y;
                    }
                }
                """);

        Method testLocal = clazz.getMethod("testLocal");
        assertEquals(42 * 3, testLocal.invoke(null));

        Method testNested = clazz.getMethod("testNested");
        // x becomes 5; y becomes 5 * 2 = 10; z = 5 + 10 = 15; z + x + y = 15 + 5 + 10 = 30
        assertEquals(30, testNested.invoke(null));
    }

    @Test
    @DisplayName("Labeled stop in void method does not omit RETURN and passes ASM verification")
    void labeledStopDoesNotOmitReturnAndPassesVerification() throws Exception {
        String code = """
                public class LabeledStopProbe {
                    public static void function test() {
                        myLabel: if (true) {
                            stop myLabel;
                        }
                    }
                }
                """;
        Map<String, byte[]> bytecode = compileToBytecodeMap(code, "LabeledStopProbe");
        for (Map.Entry<String, byte[]> entry : bytecode.entrySet()) {
            StringWriter errors = new StringWriter();
            CheckClassAdapter.verify(new ClassReader(entry.getValue()), false, new PrintWriter(errors));
            assertTrue(errors.toString().isBlank(), () -> "ASM verifier rejected " + entry.getKey() + ": " + errors);
        }

        Class<?> clazz = compileAndLoad("LabeledStopProbe", code);
        Method test = clazz.getMethod("test");
        assertDoesNotThrow(() -> test.invoke(null));
    }

    @Test
    @DisplayName("Labeled block with stop in non-void method requires return")
    void labeledBlockMissingReturnInNonVoidMethod() {
        CompilationException exception = assertThrows(CompilationException.class, () -> compileToBytecodeMap("""
                public class MissingReturnLabeled {
                    public static int function bar() {
                        myLabel: if (true) {
                            stop myLabel;
                        }
                    }
                }
                """, "MissingReturnLabeled"));
        assertTrue(exception.getMessage().contains("Missing return statement"));
    }

    @Test
    @DisplayName("Array creation with empty dimension before sized dimension fails compilation")
    void arrayCreationEmptyDimensionBeforeSizedFails() {
        CompilationException exception = assertThrows(CompilationException.class, () -> compileToBytecodeMap("""
                public class ArrayCreationIllegal {
                    public static void function bar() {
                        int[][] arr = new int[][5];
                    }
                }
                """, "ArrayCreationIllegal"));
        assertTrue(exception.getMessage().contains("empty dimension '[]'"));
    }

    @Test
    @DisplayName("Array creation with sized dimension followed by trailing empty dimension succeeds")
    void arrayCreationSizedDimensionFollowedByEmptySucceeds() throws Exception {
        Class<?> clazz = compileAndLoad("ArrayCreationTrailingEmpty", """
                public class ArrayCreationTrailingEmpty {
                    public static int function test2D() {
                        int[][] arr = new int[5][];
                        return arr.length;
                    }

                    public static int function test3D() {
                        int[][][] arr = new int[3][4][];
                        return arr.length * 10 + arr[0].length;
                    }
                }
                """);

        Method test2D = clazz.getMethod("test2D");
        assertEquals(5, test2D.invoke(null));

        Method test3D = clazz.getMethod("test3D");
        assertEquals(34, test3D.invoke(null));
    }

    @Test
    @DisplayName("Compound assignment to field evaluates receiver expression exactly once")
    void compoundAssignmentFieldReceiverEvaluatedExactlyOnce() throws Exception {
        Class<?> clazz = compileAndLoad("CompoundAssignmentReceiverProbe", """
                public class CounterTarget {
                    public int count = 10;
                    public double total = 10.0;
                    public String text = "hello";
                }

                public class CompoundAssignmentReceiverProbe {
                    public static int receiverCalls = 0;
                    public static CounterTarget target = new CounterTarget();

                    public static CounterTarget function getTarget() {
                        receiverCalls++;
                        return target;
                    }

                    public static int function testInt() {
                        receiverCalls = 0;
                        target.count = 10;
                        getTarget().count += 5;
                        return receiverCalls * 100 + target.count;
                    }

                    public static int function testExprContext() {
                        receiverCalls = 0;
                        target.count = 10;
                        int val = (getTarget().count += 7);
                        return receiverCalls * 1000 + val * 10 + target.count;
                    }

                    public static int function testDouble() {
                        receiverCalls = 0;
                        target.total = 10.0;
                        getTarget().total += 2.5;
                        return receiverCalls * 100 + (int) target.total;
                    }

                    public static String function testString() {
                        receiverCalls = 0;
                        target.text = "hello";
                        getTarget().text += " world";
                        return receiverCalls + ":" + target.text;
                    }
                }
                """);

        Method testInt = clazz.getMethod("testInt");
        // receiverCalls == 1, target.count == 15 -> 1 * 100 + 15 = 115
        assertEquals(115, testInt.invoke(null));

        Method testExprContext = clazz.getMethod("testExprContext");
        // receiverCalls == 1, val == 17, target.count == 17 -> 1 * 1000 + 17 * 10 + 17 = 1187
        assertEquals(1187, testExprContext.invoke(null));

        Method testDouble = clazz.getMethod("testDouble");
        // receiverCalls == 1, (int) target.total == 12 -> 1 * 100 + 12 = 112
        assertEquals(112, testDouble.invoke(null));

        Method testString = clazz.getMethod("testString");
        // receiverCalls == 1, text == "hello world" -> "1:hello world"
        assertEquals("1:hello world", testString.invoke(null));
    }
}


