package ocean.compiler;

import org.antlr.v4.runtime.CharStreams;
import org.antlr.v4.runtime.CommonTokenStream;
import org.antlr.v4.runtime.tree.ParseTree;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.lang.reflect.Method;
import java.lang.reflect.Modifier;
import java.util.Map;

public class NativeMethodCompilationTest {

    @BeforeEach
    public void setup() {
        CompilerReporter.clear();
        CompilerRegistry.clearAll();
    }

    private Map<String, byte[]> compileToBytecodeMap(String code, String className) throws Exception {
        CompilationSession session = new CompilationSession();
        CompilationSession.setActiveSession(session);
        try {
            OceanLexer lexer = new OceanLexer(CharStreams.fromString(code));
            lexer.removeErrorListeners();
            OceanParser parser = new OceanParser(new CommonTokenStream(lexer));
            parser.removeErrorListeners();

            ParseTree tree = parser.program();

            // Pre-scan
            PreScanner scanner = new PreScanner(className + ".ocean", session);
            scanner.setCurrentFilePackage(null);
            scanner.visit(tree);

            // IR Generation
            String detectedPackage = scanner.getCurrentFilePackage();
            IRGenerator irGen = new IRGenerator(
                className + ".ocean",
                detectedPackage,
                scanner.getImportedClasses(),
                scanner.getImportedWildcards(),
                scanner.getImportedStaticMembers(),
                scanner.getImportedStaticWildcards(),
                scanner.getSymbolTable()
            );
            ocean.compiler.ir.IRNode irTree = irGen.visit(tree);

            if (CompilerReporter.hasErrors()) {
                throw new CompilationException("Compilation failed during IR generation.");
            }

            // IR Semantic Analysis
            IRSemanticAnalyzer irAnalyzer = new IRSemanticAnalyzer(
                className + ".ocean",
                session,
                irGen.getImportedClasses(),
                irGen.getImportedWildcards(),
                irGen.getImportedStaticMembers(),
                irGen.getImportedStaticWildcards(),
                irGen.getSymbolTable()
            );
            irTree.accept(irAnalyzer);

            if (irAnalyzer.hasErrors() || CompilerReporter.hasErrors()) {
                throw new CompilationException("Compilation failed during IR semantic analysis.");
            }

            // Bytecode Emission
            IRToBytecodeEmitter emitter = new IRToBytecodeEmitter();
            irTree.accept(emitter);

            return emitter.getGeneratedClasses();
        } finally {
            CompilationSession.clearActiveSession();
        }
    }

    @Test
    public void testNativeMethodBytecodeReflection() throws Exception {
        String code =
            "package ocean.test;\n" +
            "class NativeDemo {\n" +
            "    public static native void function nativeInit(int port, String host);\n" +
            "    public native int function calculateCrc(byte[] payload);\n" +
            "    private native String function getDeviceSerial();\n" +
            "    \n" +
            "    public int function regularMethod(int x) {\n" +
            "        return x * 2;\n" +
            "    }\n" +
            "}";

        Map<String, byte[]> classes = compileToBytecodeMap(code, "NativeDemo");
        assertNotNull(classes);
        assertTrue(classes.containsKey("ocean/test/NativeDemo"));

        // Load generated bytecode
        ClassLoader cl = new ClassLoader(getClass().getClassLoader()) {
            @Override
            protected Class<?> findClass(String name) throws ClassNotFoundException {
                String internal = name.replace('.', '/');
                if (classes.containsKey(internal)) {
                    byte[] b = classes.get(internal);
                    return defineClass(name, b, 0, b.length);
                }
                return super.findClass(name);
            }
        };

        Class<?> clazz = cl.loadClass("ocean.test.NativeDemo");
        assertNotNull(clazz);

        // Verify nativeInit
        Method nativeInit = clazz.getDeclaredMethod("nativeInit", int.class, String.class);
        assertNotNull(nativeInit);
        assertTrue(Modifier.isPublic(nativeInit.getModifiers()), "nativeInit should be public");
        assertTrue(Modifier.isStatic(nativeInit.getModifiers()), "nativeInit should be static");
        assertTrue(Modifier.isNative(nativeInit.getModifiers()), "nativeInit should be native");

        // Verify calculateCrc
        Method calculateCrc = clazz.getDeclaredMethod("calculateCrc", byte[].class);
        assertNotNull(calculateCrc);
        assertTrue(Modifier.isPublic(calculateCrc.getModifiers()), "calculateCrc should be public");
        assertFalse(Modifier.isStatic(calculateCrc.getModifiers()), "calculateCrc should be instance method");
        assertTrue(Modifier.isNative(calculateCrc.getModifiers()), "calculateCrc should be native");

        // Verify getDeviceSerial
        Method getDeviceSerial = clazz.getDeclaredMethod("getDeviceSerial");
        assertNotNull(getDeviceSerial);
        assertTrue(Modifier.isPrivate(getDeviceSerial.getModifiers()), "getDeviceSerial should be private");
        assertTrue(Modifier.isNative(getDeviceSerial.getModifiers()), "getDeviceSerial should be native");

        // Verify regularMethod
        Method regularMethod = clazz.getDeclaredMethod("regularMethod", int.class);
        assertNotNull(regularMethod);
        assertFalse(Modifier.isNative(regularMethod.getModifiers()), "regularMethod should not be native");
    }

    @Test
    public void testNativeMethodWithBodyFails() {
        String code =
            "package ocean.test;\n" +
            "class InvalidNativeBody {\n" +
            "    public native int function badMethod(int x) {\n" +
            "        return x + 1;\n" +
            "    }\n" +
            "}";

        assertThrows(Exception.class, () -> compileToBytecodeMap(code, "InvalidNativeBody"));
    }

    @Test
    public void testNativeAbstractMethodFails() {
        String code =
            "package ocean.test;\n" +
            "abstract class InvalidNativeAbstract {\n" +
            "    public abstract native void function badMethod();\n" +
            "}";

        assertThrows(Exception.class, () -> compileToBytecodeMap(code, "InvalidNativeAbstract"));
    }

    @Test
    public void testNativeAsyncMethodFails() {
        String code =
            "package ocean.test;\n" +
            "class InvalidNativeAsync {\n" +
            "    public async native void function badMethod();\n" +
            "}";

        assertThrows(Exception.class, () -> compileToBytecodeMap(code, "InvalidNativeAsync"));
    }

    @Test
    public void testNativeInterfaceMethodFails() {
        String code =
            "package ocean.test;\n" +
            "interface InvalidNativeInterface {\n" +
            "    native void function badMethod();\n" +
            "}";

        assertThrows(Exception.class, () -> compileToBytecodeMap(code, "InvalidNativeInterface"));
    }
}
